print("Olá, tudo bem?")
nome = input("Digite seu nome: ")
print(" ")
print(f"Olá {nome}. Agora por favor")
idade = int(input("Digite sua idade: "))
print(" ")
print("Que legal, agora")
salario = float(input("Digite seu salário: "))
print(" ")
print(f"Olá {nome}, você tem {idade} anos de idade e recebe {salario}, dá pra melhorar.")